- name: Create Bash script from template
  template:
    src: op_token_script.j2
    dest: "{{ script_path }}"
    mode: '0700'

- name: Update .bashrc to source the Bash script
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: source {{ script_path }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR OP_SERVICE_ACCOUNT_TOKEN"
  vars:
    vault_command: "ansible-vault view --vault-password-file={{ vault_password_file_path }} {{ encrypted_file_path }}"
    vault_password_file_path: "/path/to/vault/password/file"
    encrypted_file_path: "/path/to/encrypted/file.yml"
    script_path: "/path/to/your/script.sh"
